Repository hashicorp/setup-terraform, pull requests merged in 2022-03, with the labels that each got.

#135 Update readme using github-script@v5
  README.md
Labels: documentation

#148 Update actions/github-script to v6 in README
  README.md
Labels: documentation

#153 Bump development dependencies
  dist/index.js
  dist/index1.js
  package-lock.json
  package.json
  wrapper/package-lock.json
  wrapper/package.json
Labels: dependencies

#147 Allow proxy values to be set
  dist/bridge.js
  dist/events.js
  dist/index.js
  dist/setup-node-sandbox.js
  dist/setup-sandbox.js
  package-lock.json
  package.json
Labels: dependencies

#129 Improve output for PR comment
  README.md
Labels: enhancement

#160 Bump @actions/core from 1.2.7 to 1.6.0
  dist/index1.js
  wrapper/package-lock.json
  wrapper/package.json
Labels: dependencies

#162 Bump @actions/io from 1.1.0 to 1.1.1
  dist/index1.js
  wrapper/package-lock.json
  wrapper/package.json
Labels: dependencies
