Repository hashicorp/setup-terraform, pull requests merged in 2022-04, with the labels that each got.

#173 Add GitHub automatic release
  .github/release.yml
  .github/workflows/release.yml
Labels: build

#175 Release 1.4.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: build

#178 docs: update existing PR comments example
  README.md
Labels: documentation

#176 Update Terraform versions and usage in README examples
  README.md
Labels: documentation

#170 Upgrade Nodejs runtime from 12 to 16
  .github/workflows/continuous-integration.yml
  .github/workflows/setup-terraform.yml
  action.yml
  dist/index.js
  package-lock.json
  wrapper/package-lock.json
Labels: dependencies

#180 Update README.md
  README.md
Labels: documentation

#179 dependabot: track github-actions dependency changes
  .github/dependabot.yml
Labels: ci

#181 Release 2.0.0
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
Labels: enhancement
